version: "3.8"

services:
  product_service:
    image: solcr/ktpm-server-product-service:test
    restart: on-failure
    ports:
      - "10000:10000"
    volumes:
      - ./product_service.config.yaml:/config.yaml:ro