SERVER:
  GRPC:
    PORT: 9443
  HTTP:
    PORT: 8080

ORDER_SERVICE_ADDR: 0.0.0.0:9443
ACCOUNT_SERVICE_ADDR: 0.0.0.0:9444

MIGRATION_FOLDER: file://sql/migrations

WAREHOUSE_SERVICE_DB:
  HOST: 127.0.0.1
  PORT: 8878
  USERNAME: postgres
  PASSWORD:
  DATABASE: warehouse
  OPTIONS: ?sslmode=disable