SERVER:
  GRPC:
    PORT: 9443
  HTTP:
    PORT: 8080

MIGRATION_FOLDER: file://sql/migrations

WMS_ODOO_SERVICE_DB:
  HOST: 127.0.0.1
  PORT: 5432
  USERNAME: vungocthach
  PASSWORD: 111200
  DATABASE: warehouse_service
  OPTIONS: ?sslmode=disable