SERVER:
  GRPC:
    PORT: 9444
  HTTP:
    PORT: 8081

MIGRATION_FOLDER: file://sql/migrations

ACCOUNT_SERVICE_DB:
  HOST: 127.0.0.1
  PORT: 101010
  USERNAME: postgres
  PASSWORD: postgres123
  DATABASE: account
  OPTIONS: ?sslmode=disable