// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: import.sql

package store

import (
	"context"
)

const getImportBills = `-- name: getImportBills :many
SELECT id, code, note, contact_person_name, contact_email, contact_phone, create_uid, create_date, write_uid, write_date
FROM import_bill
`

func (q *Queries) getImportBills(ctx context.Context) ([]ImportBill, error) {
	rows, err := q.query(ctx, q.getImportBillsStmt, getImportBills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportBill{}
	for rows.Next() {
		var i ImportBill
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Note,
			&i.ContactPersonName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CreateUid,
			&i.CreateDate,
			&i.WriteUid,
			&i.WriteDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
