// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
)

type Querier interface {
	getImportBills(ctx context.Context) ([]ImportBill, error)
}

var _ Querier = (*Queries)(nil)
