// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"context"
)

type Querier interface {
	getImportBillDetails(ctx context.Context, arg getImportBillDetailsParams) ([]ImportBillDetail, error)
	getImportBills(ctx context.Context, ids []int64) ([]ImportBill, error)
}

var _ Querier = (*Queries)(nil)
