SERVER:
  GRPC:
    PORT: 9445
  HTTP:
    PORT: 8082

MIGRATION_FOLDER: file://sql/migrations

ORDER_SERVICE_DB:
  HOST: 127.0.0.1
  PORT: 5432
  USERNAME: vungocthach
  PASSWORD: 111200
  DATABASE: ecommerce_order
  OPTIONS: ?sslmode=disable