SERVER:
  GRPC:
    PORT: 11000
  HTTP:
    PORT: 10000

MIGRATION_FOLDER: file://database/migrations

PRODUCT_SERVICE_DB:
  HOST: 127.0.0.1
  PORT: 10102
  USERNAME: postgres
  PASSWORD: postgres123
  DATABASE: product
  OPTIONS: ?sslmode=disable

KAFKA_CONFIG:
  CONNECTIONS:
    - 'localhost:9092'
    - 'localhost:9093'

MEM_CACHE_CONFIG:
  MAX_TIME_MISS: 3
  MAX_CACHE_SIZE_IN_MB: 3072
  EXPIRED_TIME_IN_SECOND: 600
  TIME_BETWEEN_CLEAN_EXPIRED_IN_SECOND: 300
  SHARDS: 1024

REDIS_CONFIG:
  ADDR: 'localhost:6379'
  PASSWORD: 'redis@123'
  NUMBER_CACHE_PAGE: 5
  EXPIRE_CACHE_PAGE_IN_SECOND: 600

ENABLE_CACHE: true # if true, check ENABLE_MEM and ENABLE_REDIS, else ignore all
ENABLE_MEM: true
ENABLE_REDIS: false
CONN_MAX_TIME_IDLE_IN_SECOND: 0