version: "3.8"

services:
  pg_master:
    image: bitnami/postgresql:12
    ports:
      - "8888:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=demo_repl
      - POSTGRESQL_REPLICATION_PASSWORD=123qwe_repl
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123qwe
      - POSTGRESQL_DATABASE=warehouse
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  pg_slave:
    image: bitnami/postgresql:12
    ports:
      - "8878:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=demo_repl
      - POSTGRESQL_REPLICATION_PASSWORD=123qwe_repl
      - POSTGRESQL_MASTER_HOST=pgs_master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  master_data:
