SERVER:
  GRPC:
    PORT: 11001
  HTTP:
    PORT: 10001

MIGRATION_FOLDER: file://internal/database/migrations

PRODUCT_SERVICE_DB:
  HOST: 127.0.0.1
  PORT: 10102
  USERNAME: postgres
  PASSWORD: postgres123
  DATABASE: product
  OPTIONS: ?sslmode=disable

KAFKA_CONFIG:
  CONNECTIONS:
    - LOCALHOST:9092
    - LOCALHOST:9093
  MAX_PUBLISH_TIMEOUT_IN_SECOND: 10
  MAX_NUMBER_RETRY: 3
  TIME_SLEEP_PER_REQUEST_MILLISECOND: 200